### ISSUE TITLE
Unable to connect to Exchange Online

### ISSUE THREAD

**Issue by mklifman** [maester365/maester#651]
I am unable to connect to Exchange Online when running the Maester tests via Github actions.

![Image](https://github.com/user-attachments/assets/82ae7a44-9148-4566-8298-369b67880bdb)

I followed the steps as mentioned here: https://maester.dev/docs/monitoring/github 

API permissions configured in the application:

![Image](https://github.com/user-attachments/assets/3c620aca-932f-4d8a-ac58-5ca98eba3c7a)

The PowerShell cmdlets are also run, but still getting that it could not connect to Exchange Online.

**Comment by soulemike** [comment]
I do not believe the current GHA image does not have the dependent modules (Ref #494)

**Comment by maikvandergaag** [comment]
Have the exact same problem. Is this something that is not supported? I also tried to connect to exchange online seperatly, but then receive a 'NotAuthorized' exception.

**Comment by maikvandergaag** [comment]
@mklifman it has to do with the fact that it is not build-in to the actions at this moment.

What I have done to get the Exchange test working is add the connection to Exchange manually. At the moment I am working a a new version of the Action to include exchange and the others like Security and Teams.

Will create a pull request when ready. If you need any code to get started let me know.

**Comment by makiv2** [comment]
Do you have any tips on getting the Exchange tests to work? I can't get the Connect-ExchangeOnline command to run, which causes the Get-OwaMailboxPolicy cmdlet to be unavailable.

@maikvandergaag Additionally, I need to automate this within an Azure pipeline, so manual authentication isn't an option. The tests work with manual authentication, but they fail in ADO.

**Comment by maikvandergaag** [comment]
I have adjusted the powershell within the action also perform the exchange online stuff. 

I am on the road so unable to share the script I will add the powershell to the issue tomorrow when I am back

**Comment by makiv2** [comment]
Okay thanks, much appreciated! @maikvandergaag

**Comment by soulemike** [comment]
> Okay thanks, much appreciated! [@maikvandergaag](https://github.com/maikvandergaag)

@makiv2 does the guidance in the advanced connection docs provide assistance?

https://github.com/maester365/maester/issues/636#issuecomment-2646356435

**Comment by maikvandergaag** [comment]
Hi Guys,

This is the script I have used within a GitHub Action

``` ps
            Install-Module Maester -Force
            Install-Module ExchangeOnlineManagement -Force

            Import-Module ExchangeOnlineManagement

            # Get Token
            $token = az account get-access-token --resource-type ms-graph

            # Connect to Microsoft Graph
            $accessToken = ($token | ConvertFrom-Json).accessToken | ConvertTo-SecureString -AsPlainText -Force
            $outlookToken = (Get-AzAccessToken -ResourceUrl 'https://outlook.office365.com/').Token
            Connect-MgGraph -AccessToken $accessToken -NoWelcome
            Connect-ExchangeOnline -AccessToken $outlookToken -AppId '${{ secrets.AZURE_CLIENT_ID }}' -Organization '${{ secrets.AZURE_TENANT_ID}}' -ShowBanner:$false -Verbose


            # Configure test results
            $PesterConfiguration = New-PesterConfiguration
            $PesterConfiguration.Output.Verbosity = 'None'
            Write-Host "Pester verbosity level set to: $($PesterConfiguration.Output.Verbosity.Value)"

            $MaesterParameters = @{
                Path                 = '${{ github.workspace }}'
                PesterConfiguration  = $PesterConfiguration
                OutputFolder         = 'test-results'
                OutputFolderFileName = 'test-results'
                PassThru             = $true
            }

            # Check if mail recipients and mail userid are provided
            if ( [string]::IsNullOrWhiteSpace( '${{ vars.MAESTER_FROMEMAIL }}' ) -eq $false ) {
                if ( [string]::IsNullOrWhiteSpace( '${{ vars.MAESTER_EMAILS }}' ) -eq $false ) {
                    # Add mail parameters
                    $MaesterParameters.Add( 'MailUserId', '${{ vars.MAESTER_FROMEMAIL }}' )
                    $Recipients = '${{ vars.MAESTER_EMAILS }}' -split ','
                    $MaesterParameters.Add( 'MailRecipient', $Recipients )
                    $MaesterParameters.Add( 'MailTestResultsUri', '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}' )
                    Write-Host "Mail notification will be sent to: $Recipients"
                } else {
                    Write-Warning "Mail recipients are not provided. Skipping mail notification."
                }
            }

            # Run Maester tests
            $results = Invoke-Maester @MaesterParameters

            # Add step summary
            $summary = Get-Content test-results/test-results.md
            Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value $summary


```

**Comment by mklifman** [comment]
@maikvandergaag Thanks for the script! Much appreciated.

I assume that you have opted for the option that the MaesterTests are running from your own GitHub and need to update your MaesterTests manually instead of always using the lastest available?

**Comment by maikvandergaag** [comment]
@mklifman: I was running it with the latest available in combination with some custom tests.

**Comment by merill** [comment]
Here are the links to the docs. 

I believe we should be able to get it working with at least client id and secret as a first step, then certs and preferably workload id federation.

Once you get it working can you help update the docs and the GitHub Action? Tx

For Teams - [learn.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps#example-6-connect-to-microsoftteams-using-application-based-access-tokens](https://learn.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps#example-6-connect-to-microsoftteams-using-application-based-access-tokens)

For ExchangeOnline the docs are at - [learn.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps](https://learn.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps)

**Comment by maikvandergaag** [comment]
Teams should already be working. The one that isn't working is the Security & Compliance rules. The actions now get the tokens based on the already logged-in application.

The Connect-IPPSSession does not have the option to supply it with a token. This means that the Certificate needs to be saved somewhere in order to sign in. I was hoping to get it done without saving too much authentication information.

I will check in the coming weeks to see if I can make some adjustments.

**Comment by soulemike** [comment]
The Container App Job docs, show an example of securely using cert auth. https://maester.dev/docs/monitoring/azure-container-app-job#configure-certificate-based-authentication-for-your-service-principal

The M365DSC project has a good table outlining the authentication methods available by the upstream modules for reference too. https://microsoft365dsc.com/user-guide/get-started/authentication-and-permissions/#authentication-methods

**Comment by tacoroumen** [comment]
Hey all,
For me Teams integration still doesn't work it just skips and says "Skipped. Not connected to Teams. See [Connecting to Teams]" Do you have any things it could be. Also MS.AAD.4.1 doesn't seem to work because of "Skipped. Not connected to Azure. See [Connecting to Azure](https://maester.dev/docs/connect-maester/#connect-to-azure-exchange-online-and-teams)" how is it not connected to azure? I have followed all setup docs as stated [here](https://maester.dev/docs/monitoring/github) i have also updated the script to the one provided in this issue [here](https://github.com/maester365/maester/issues/651#issuecomment-2647137154) for me this looks like this: 


```
          Install-Module Maester -Force
          Install-Module ExchangeOnlineManagement -Force

          Import-Module ExchangeOnlineManagement

          # Get Token
          $token = az account get-access-token --resource-type ms-graph

          # Connect to Microsoft Graph
          $accessToken = ($token | ConvertFrom-Json).accessToken | ConvertTo-SecureString -AsPlainText -Force
          $outlookToken = (az account get-access-token --resource https://outlook.office365.com --query accessToken -o tsv)
          #$outlookToken = (Get-AzAccessToken -ResourceUrl 'https://outlook.office365.com/').Token
          Connect-MgGraph -AccessToken $accessToken -NoWelcome
          Connect-ExchangeOnline -AccessToken $outlookToken -AppId '${{ secrets.AZURE_CLIENT_ID }}' -Organization '${{ secrets.AZURE_TENANT_ID}}' -ShowBanner:$false -Verbose


          # Configure test results
          $PesterConfiguration = New-PesterConfiguration
          $PesterConfiguration.Output.Verbosity = 'None'
          Write-Host "Pester verbosity level set to: $($PesterConfiguration.Output.Verbosity.Value)"

          $MaesterParameters = @{
              Path                 = '${{ github.workspace }}'
              PesterConfiguration  = $PesterConfiguration
              OutputFolder         = 'test-results'
              OutputFolderFileName = 'test-results'
              PassThru             = $true
          }

          # Check if mail recipients and mail userid are provided
          if ( [string]::IsNullOrWhiteSpace( '${{ secrets.MAIL_USERID }}' ) -eq $false ) {
              if ( [string]::IsNullOrWhiteSpace( '${{ secrets.MAIL_RECIPIENT }}' ) -eq $false ) {
                  # Add mail parameters
                  $MaesterParameters.Add( 'MailUserId', '${{ secrets.MAIL_USERID }}' )
                  $Recipients = '${{ secrets.MAIL_RECIPIENT }}' -split ','
                  $MaesterParameters.Add( 'MailRecipient', $Recipients )
                  $MaesterParameters.Add( 'MailTestResultsUri', '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}' )
                  Write-Host "Mail notification will be sent to: $Recipients"
              } else {
                  Write-Warning "Mail recipients are not provided. Skipping mail notification."
              }
          }

          # Run Maester tests
          $results = Invoke-Maester @MaesterParameters

          # Add step summary
          $summary = Get-Content test-results/test-results.md
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value $summary 
```

**Comment by tacoroumen** [comment]
@maikvandergaag i only have the test repo cloned as in [maester-tests](https://github.com/maester365/maester-tests) how would i go about calling this script from my action in here or should i clone the full maester repo?

**Comment by tacoroumen** [comment]
@maikvandergaag when running this script i get the following error:

```
Get-AzAccessToken: /home/runner/work/maester-tests/maester-tests/Run-Maester.ps1:50
Line |
  50 |  … raphToken = Get-AzAccessToken -ResourceUrl 'https://graph.microsoft.c/ …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Run Connect-AzAccount to login.
Error: Error: The process '/usr/bin/pwsh' failed with exit code 1
```

**Comment by maikvandergaag** [comment]
That's correct you need to be logged in before running this script.

**Comment by tacoroumen** [comment]
@maikvandergaag My bad i didn't add my authentication step just added it in my comment above

**Comment by maikvandergaag** [comment]
You should add enable-AzPSSession: true to the step

**Comment by tacoroumen** [comment]
The azure skip went away but teams is still skipped however now it returns an error in the action log:

```
Get-CsTeamsMeetingPolicy: /home/runner/work/maester-tests/maester-tests/tests/Maester/Teams/Test-TeamsMeeting.Tests.ps1:4
Line |
   4 |          $TeamsMeetingPolicy = Get-CsTeamsMeetingPolicy
     |                                ~~~~~~~~~~~~~~~~~~~~~~~~
     | Access Denied. Provide different credential or request access.
```

do i need to add some other api permision?

![Image](https://github.com/user-attachments/assets/89697d37-ca94-47ab-aa01-9687fac7a015)

**Comment by maikvandergaag** [comment]
Yes I think so not totally sure on what permissions are required for teams.

**Comment by makiv2** [comment]
The teams module does not use api permissions, you need to assign the app registration the appropriate RBAC role.

Had the same issue and it says somewhere in the docs of the Teams module, on the phone so I cant find it on the go.

**Comment by tacoroumen** [comment]
Thx. this fixed my teams issues! Has anyone been able to get Security & Compliance to work with an application login? I have found this https://microsoft365dsc.com/user-guide/get-started/authentication-and-permissions/#security-and-compliance-center-permissions and have followed these steps however it still wont connect do I need to change something else or is this not possible yet?

**Comment by makiv2** [comment]
Yes, I have Security & Compliance working,

`Connect-IPPSSession -Certificate $cert -AppID $clientid -Organization $moera`

<img width="793" alt="Image" src="https://github.com/user-attachments/assets/05d28b7e-528f-4b43-8368-d362bacd6ff9" />

If I remember correctly the cmdlets are "not found" when there is an permission issue making it a bit confusing. I gave my app reg global reader to avoid all these issues.

**Comment by FundMSG** [comment]
I have a problem with connecting to "Security and Compliance."  and Teams

Exchange online is connecting with below.
New-ServicePrincipal -AppId <Application ID> -ObjectId <Object ID> -DisplayName <Name>
New-ManagementRoleAssignment -Role "View-Only Configuration" -App <DisplayName from previous command>

In Maester code change **include_exchange: true**

name: Maester Daily Tests

on:
  push:
    branches: ["main"]
  # Run once a day at midnight
  schedule:
    - cron: "0 0 * * *"
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
      checks: write

jobs:
  run-maester-tests:
    name: Run Maester Tests
    runs-on: ubuntu-latest
    steps:
    - name: Run Maester action
      uses: maester365/maester@main
      with:
        client_id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        include_public_tests: true # Optional: Set to false if you are keeping to a certain version of tests or have your own tests
        include_exchange: true    # Optional: Set to true to include the Exchange tests
        step_summary: true         # Optional: Set to false if you don't want a summary added to your GitHub Action run
        artifact_upload: true      # Optional: Set to false if you don't want summaries uploaded to GitHub Artifacts
        install_prerelease: false  # Optional: Set to true if you want to use Measter Preview Build when running tests
        disable_telemetry: false   # Optional: Set to true If you want telemetry information not to be logged.
        # Other inputs are available and can be reviewed in the action.yml in the Maester repository

**Comment by FundMSG** [comment]
Teams is connecting with below steps.

https://learn.microsoft.com/en-us/microsoftteams/teams-powershell-application-authentication

Setup Application-based authentication
An initial onboarding is required for authentication using application objects. Application and service principal are used interchangeably, but an application is like a class object while a service principal is like an instance of the class. You can learn more about these objects at [Application and service principal objects in Microsoft Entra ID](https://learn.microsoft.com/en-us/azure/active-directory/develop/app-objects-and-service-principals).

Sample steps for creating applications in Microsoft Entra ID are mentioned below. For detailed steps, refer to this [article](https://learn.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal).

Register the application in Microsoft Entra ID.
Assign API permissions to the application.
For *-Cs cmdlets - The Microsoft Graph API permission needed is Organization.Read.All.
For Non *-Cs cmdlets - The Microsoft Graph API permissions needed are Organization.Read.All, User.Read.All, Group.ReadWrite.All, AppCatalog.ReadWrite.All, TeamSettings.ReadWrite.All, Channel.Delete.All, ChannelSettings.ReadWrite.All, ChannelMember.ReadWrite.All.
Note - There's no need to configure any API permission for "Skype and Teams Tenant Admin API". Configuring this permission might result in failures.

Generate a self-signed certificate.

Attach the certificate to the Microsoft Entra application.

Assign [Microsoft Entra roles](https://learn.microsoft.com/en-us/microsoftteams/using-admin-roles#teams-roles-and-capabilities) to the application. Refer to this [Assign a role](https://learn.microsoft.com/en-us/azure/active-directory/roles/manage-roles-portal#assign-a-role) procedure, but search for the application instead of a user.
